apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vishalpuri01/backend:v3
        env:
        - name: MONGO_URI
          value: "mongodb://localhost:27017/" 
        ports:
        - containerPort: 5000
