apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vishalpuri01/frontend:v3.1
        env:
        - name: BACKEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_API_URL
        ports:
        - containerPort: 3000
